eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9090
spring:
  application:
    name: datacenter
  datasource:
        username: root
        password: root
        url: jdbc:mysql://localhost:3306/eladmin?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
        driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.asiainfo.security.entity
#showSql
logging:
  level:
    com:
      example:
        mapper : debug
#//ghghhgh