eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9090
spring:
  application:
    name: datacenter
  data:
      mongodb:
        uri: mongodb://dev:sdyx2019@47.105.40.83:20887/test
